steps:
  # deploy container image to GKE
  - name: "gcr.io/cloud-builders/kubectl"
    id: Deploy
    args:
      - "apply"
      - "-f"
      - "kubernetes.yaml"
    env:
      - "CLOUDSDK_COMPUTE_REGION=europe-west3"
      - "CLOUDSDK_CONTAINER_CLUSTER=cloudkite-interview-cluster"

  # Set up git with key and domain
  - name: "gcr.io/cloud-builders/git"
    id: Accessing GitHub secret
    entrypoint: "bash"
    args:
      - "-c"
      - |
        ssh-keyscan -t rsa github.com > known_hosts.github
    volumes:
      - name: "ssh"
        path: /root/.ssh
  # Set up git with key and domain
  - name: "gcr.io/cloud-builders/git"
    secretEnv: ["SSH_KEY"]
    id: Copying Github secret
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "$$SSH_KEY\n" >> /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        cp known_hosts.github /root/.ssh/known_hosts
    volumes:
      - name: "ssh"
        path: /root/.ssh
  # This step copies the applied manifest to the production branch
  # The COMMIT_SHA variable is automatically
  # replaced by Cloud Build.
  - name: "gcr.io/cloud-builders/git"
    id: Copy to production branch
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        set -x && \
        # Configure Git to create commits with Cloud Build's service account
        git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)') && \
        # Switch to the production branch and copy the kubernetes.yaml file from the candidate branch
        git fetch origin production && git checkout production && \
        git checkout $COMMIT_SHA kubernetes.yaml && \
        # Commit the kubernetes.yaml file with a descriptive commit message
        git commit -m "Manifest from commit $COMMIT_SHA
        $(git log --format=%B -n 1 $COMMIT_SHA)" && \
        git remote set-url origin git@github.com:martinmbaya/cloudkite-interview-env.git && \
        # Push the changes back to Cloud Source Repository
        git push origin production
    volumes:
      - name: "ssh"
        path: /root/.ssh
